chore: run "nix flake update"
sphinx_rtd_theme has been renamed to sphinx-rtd-theme

Moving pthreads to buildInputs fixes this error:

       error: Refusing to evaluate package 'mingw_w64-pthreads-13.0.0' in /nix/store/f78lkqnk63pd0kf52zf2wcx35p1nnalr-source/pkgs/os-specific/windows/mingw-w64/headers.nix:35 because it is not available on the requested hostPlatform:
         hostPlatform.system = "x86_64-linux"
         package.meta.platforms = [
           "aarch64-windows"
           "x86_64-windows"
           "i686-windows"
         ]
         package.meta.badPlatforms = [ ]